### ISSUE TITLE
Help needed?

### ISSUE THREAD

**Issue by BlackIQ** [mmjsys/The-Cuckoo-s-Egg-#1]
Hi.
You know I liked your idea. To make progress in this journey, you cant do it in your own.
So I offer you to do it together with some translators.
BYW: I am one of people in headquarter of translating Django for professionals.
Anyway, if you attracted of this offer, contact me and we will talk more.
Email: amirhosseinmohammadi1380@yahoo.com
Telegram: [@BlackIQ](https://t.me/BlackIQ)
Phone: +989014784362

**Comment by mmjsys** [comment]
hello .
if you want to actualize this idea  .
not problem . 😁
create repo and work on it .
I haven't time to translate it  .

‫‪AmirHossein Mohammadi‬‏ ***@***.***‬‏> در تاریخ یکشنبه ۱۲
دسامبر ۲۰۲۱ ساعت ۰:۳۰ نوشت:‬
